baseurl = "https://laynalingam.github.io"
defaultContentLanguage = "en"
languageCode = "en"
title = "Layna Lingam"
theme = "dream"


[services]
# [services.disqus]
# shortname = "laynalingam"

[services.googleAnalytics]
ID = "JXR68YGYKQ"

[params]
 zenMode = false

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = ""
# backgroundImageDark = ""

author = "Layna Lingam"
description = "Layna Lingam's Website"
avatar = "img/laynalingam.webp"
headerTitle = "Layna Lingam"
motto = "Layna's Sensual Escapedes"

footerBottomText = "Layna 2024 Copyright | All Rights Reserved"

# rss = true

utterancesRepo = "laynalingam/laynalingam.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "laynalingam@gmail.com"

siteStartYear = 2016

favicon = "img/favicon.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = false
reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
reorderShares = ["x", "youtube", "whatsapp"]

# [[params.navItems]]

# [params.advanced]
#customCSS = ["css/custom.css"]
#customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy-MM-dd"